// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAev__FPd2lcGleH9jR5HFbQ3TU46xTiOI',
    appId: '1:1010379975924:web:157d29fcd02871991182a1',
    messagingSenderId: '1010379975924',
    projectId: 'nowingdev',
    authDomain: 'nowingdev.firebaseapp.com',
    storageBucket: 'nowingdev.appspot.com',
    measurementId: 'G-4VNC7HWMQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBitMu-iYbC0D7H3Atir8I6pTmP-4kF_RI',
    appId: '1:1010379975924:android:3ab77d1741b80c761182a1',
    messagingSenderId: '1010379975924',
    projectId: 'nowingdev',
    storageBucket: 'nowingdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmOmbF2dRadlv8JMsEqqliCpqvrndu8BI',
    appId: '1:1010379975924:ios:d50435d66a844ff11182a1',
    messagingSenderId: '1010379975924',
    projectId: 'nowingdev',
    storageBucket: 'nowingdev.appspot.com',
    androidClientId: '1010379975924-5kpds66mordmicp1q78jqd1rjjilq7ej.apps.googleusercontent.com',
    iosClientId: '1010379975924-kf06dpkijinhpv509i2tsi3bffshg9ki.apps.googleusercontent.com',
    iosBundleId: 'com.manasmalla.nowingoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmOmbF2dRadlv8JMsEqqliCpqvrndu8BI',
    appId: '1:1010379975924:ios:5e82169449afe0d61182a1',
    messagingSenderId: '1010379975924',
    projectId: 'nowingdev',
    storageBucket: 'nowingdev.appspot.com',
    androidClientId: '1010379975924-5kpds66mordmicp1q78jqd1rjjilq7ej.apps.googleusercontent.com',
    iosClientId: '1010379975924-ie7jlc4vsq1o3qesdhvu7dg9gb6iaepi.apps.googleusercontent.com',
    iosBundleId: 'com.manasmalla.nowingoogle.RunnerTests',
  );
}
